[id='early-access_{context}']
= Early Access Release

VPP is being released on Red Hat Enterprise Linux (RHEL) as an Early Access Release.
This gives customers a chance to install VPP on RHEL via Subscription Manager and test with VPP on RHEL.
*VPP is currently not a Red Hat supported product.*
If issues arise during installation of VPP on RHEL, please submit a Red Hat Bugzilla ticket (see <<Report Issue to Red Hat>>).
All other issues should be addressed with the upstream community (see <<Report Issue to Upstream VPP>>).


== Report Issue to Red Hat
:link-to-rhel-7-bugzilla: https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207

Red Hat uses Bugzilla as a bug reporting system.
Red Hat Bugzilla requires a legitimate login to submit a ticket.
To submit a Bugzilla ticket for VPP issues specific to RHEL, report using the following link:

[none]
* {link-to-rhel-7-bugzilla}

To manually get to the same link:

. Use link: https://bugzilla.redhat.com/
. Follow link in upper right labeled: **Enter a new bug report**
. Enter the classification. Select either: **All** or **Red Hat**
. Enter the Red Hat Product. Select: **Red Hat Enterprise Linux 7**


At this point, enter details regarding issue:

. Enter the Component. Select: **vpp**
. Enter the Version. Select the RHEL Version in use.
. Enter a Summary and Description of issue.
. Once details have been entered, use the **Submit Bug** button. 


== Report Issue to Upstream VPP

Upstream VPP uses Jira as a bug reporting system. The VPP Wiki has a page describing how to enter a trouble ticket:

[none]
* Wiki Page: https://wiki.fd.io/view/VPP/BugReports
* VPP JIRA: https://jira.fd.io/browse/VPP

As the Wiki page states, it is best to follow-up any Jira tickets with a short description of the issue in an email to vpp-dev@lists.fd.io.
