[id='hardware-requirements_{context}']
= Hardware Requirements

// Included in:

The minimum and recommended hardware requirements are outlined here. In general, VPP is highly configurable and can run on a high range of systems including bare metal, VM, and container, as well with a variety of CPU families. As expected, the newer and more powerfully the CPU, and the more CPUs dedicated to VPP, the higher the packet throughput and better the performance.

.VPP Hardware Requirements
[options="header"]
|====
|Resource |Minimum |Recommended
|CPU |A dual core CPU. |A quad core CPU or multiple dual core CPUs.
|Memory - Hugepage Support |Number of Pages: 512  Pagesize: 2048 kB |Number of Pages: 1024  Pagesize: 2048 kB
|Hard Disk |500 MB of locally accessible, writable disk space. |2 GB of locally accessible, writable disk space.
|Network Interface |See below. |See below.
|====

Because VPP can run in different environments, the Network Interface requirements vary per environment. On bare-metal, by default, VPP uses another open source library, DPDK, to manage the physical NICs. Use link:http://doc.dpdk.org/guides-18.02/nics/index.html[Network Interface Controller Drivers] from DPDK to determine the set of NICs supported and set of features for each.

